[server]
host = "127.0.0.1"
port = 8080
workers = 4
keep_alive = 30
max_connections = 1000

[ai_core]
url = "http://127.0.0.1:8000"
timeout_seconds = 300
retry_attempts = 3
retry_delay_ms = 1000

[cors]
allowed_origins = ["http://localhost:1420", "http://127.0.0.1:1420"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["*"]
max_age = 3600

[database]
connection_string = "mongodb://localhost:27017"
database_name = "genesis"
collections = { projects = "projects" }

[logging]
level = "info"
format = "json"
file = "logs/backend.log"
max_files = 5
max_size_mb = 10

[security]
rate_limit_requests = 100
rate_limit_window_seconds = 60
max_request_size_mb = 10

[projects]
storage_dir = "projects"
max_projects_per_user = 100
cleanup_old_projects_days = 30 