[server]
host = "127.0.0.1"
port = 8080

[ai_core]
url = "http://127.0.0.1:8000"
timeout_seconds = 300

[cors]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE"]
allowed_headers = ["*"] 